// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMIFLIZ7HXZZ6QFm8Wr0g3K2NUj_YdTBA',
    appId: '1:130916575737:web:9b56abfbb6a9635e9ff528',
    messagingSenderId: '130916575737',
    projectId: 'expensetrackerflask',
    authDomain: 'expensetrackerflask.firebaseapp.com',
    databaseURL: 'https://expensetrackerflask-default-rtdb.firebaseio.com',
    storageBucket: 'expensetrackerflask.firebasestorage.app',
    measurementId: 'G-30D6J4KM1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7x-m-9O1hXdGzyz9ETZBlj1CS9J5SGSk',
    appId: '1:130916575737:android:749c70b22545e5ad9ff528',
    messagingSenderId: '130916575737',
    projectId: 'expensetrackerflask',
    databaseURL: 'https://expensetrackerflask-default-rtdb.firebaseio.com',
    storageBucket: 'expensetrackerflask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUxkqLJSpWgeirL2_b2WdsXtMHiZcWhc',
    appId: '1:130916575737:ios:e99c520d7b358b109ff528',
    messagingSenderId: '130916575737',
    projectId: 'expensetrackerflask',
    databaseURL: 'https://expensetrackerflask-default-rtdb.firebaseio.com',
    storageBucket: 'expensetrackerflask.firebasestorage.app',
    iosClientId: '130916575737-gnlbv31spfiivi0inrf5kvpcdkllf1tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUxkqLJSpWgeirL2_b2WdsXtMHiZcWhc',
    appId: '1:130916575737:ios:e99c520d7b358b109ff528',
    messagingSenderId: '130916575737',
    projectId: 'expensetrackerflask',
    databaseURL: 'https://expensetrackerflask-default-rtdb.firebaseio.com',
    storageBucket: 'expensetrackerflask.firebasestorage.app',
    iosClientId: '130916575737-gnlbv31spfiivi0inrf5kvpcdkllf1tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMIFLIZ7HXZZ6QFm8Wr0g3K2NUj_YdTBA',
    appId: '1:130916575737:web:5a1469ca5f239eee9ff528',
    messagingSenderId: '130916575737',
    projectId: 'expensetrackerflask',
    authDomain: 'expensetrackerflask.firebaseapp.com',
    databaseURL: 'https://expensetrackerflask-default-rtdb.firebaseio.com',
    storageBucket: 'expensetrackerflask.firebasestorage.app',
    measurementId: 'G-FE99F62LDX',
  );
}
